### ISSUE TITLE
Grid 栅格组件自适应在ssr中无效 

### ISSUE THREAD

**Issue by nickliya** [Zolyn/Ephemeres#2]
你好，我在寻找vite ssr +naive-ui的解决方案
看到了你的这个demo
我在使用Grid 栅格的时候发现ssr不支持自适应。请问你这边也是这样吗？

我仅仅是替换了你layouts下的default.vue文件
```js
<template>
    <n-divider>Self 响应式</n-divider>
    <n-grid cols="4" item-responsive>
        <n-grid-item span="0 400:1 600:2 800:3">
            <div class="light-green">
                0～400px：不显示<br />
                400～600px：占据空间 1<br />
                600～800px：占据空间 2<br />
                800px 以上：占据空间 3
            </div>
        </n-grid-item>
        <n-grid-item>
            <!-- <div class="green">2</div> -->
            <router-view></router-view>
        </n-grid-item>
    </n-grid>
    <n-divider>Screen 响应式</n-divider>
    <n-grid cols="4" item-responsive responsive="screen">
        <n-grid-item span="0 m:1 l:2">
            <div class="light-green">
                m 以下：不显示<br />
                m 到 l：占据空间 1<br />
                l 以上：占据空间 2
            </div>
        </n-grid-item>
        <n-grid-item>
            <div class="green">2</div>
        </n-grid-item>
    </n-grid>
</template>

<style>
.light-green {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 200px;
    background-color: rgba(0, 128, 0, 0.12);
}
.green {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 200px;
    background-color: rgba(0, 128, 0, 0.24);
}
</style>
```

![image](https://user-images.githubusercontent.com/31945560/151643347-1c997102-a866-448b-8e6b-8f53fca5a6ba.png)
我觉得这应该是naive-ui的问题
不知道你那边是不是也这样，能否帮忙看看

**Comment by Zolyn** [comment]
![2022-01-29_16-00](https://user-images.githubusercontent.com/35414841/151653035-6497c381-62dd-4435-a1fb-0a590907a1ba.png)
![2022-01-29_16-00_1](https://user-images.githubusercontent.com/35414841/151653038-777fdb65-86ab-4d97-bf80-4fa7fcd44e78.png)

看起来是能正常工作的

另附上依赖版本
![2022-01-29_16-01](https://user-images.githubusercontent.com/35414841/151653046-0cb16b67-c681-4442-8215-621fded19322.png)

**Comment by Zolyn** [comment]
> ![2022-01-29_16-00](https://user-images.githubusercontent.com/35414841/151653035-6497c381-62dd-4435-a1fb-0a590907a1ba.png) ![2022-01-29_16-00_1](https://user-images.githubusercontent.com/35414841/151653038-777fdb65-86ab-4d97-bf80-4fa7fcd44e78.png)
> 
> 看起来是能正常工作的
> 
> 另附上依赖版本 ![2022-01-29_16-01](https://user-images.githubusercontent.com/35414841/151653046-0cb16b67-c681-4442-8215-621fded19322.png)

抱歉，本地有一些修改忘commit了，现在已经push了，你能再看看还有没有这个问题吗？

**Comment by nickliya** [comment]
yarn dev 
yarn build
yarn serve
均可行，非常感谢

但仍有很多看不明白的地方，我再慢慢研究学习下，感谢！
